[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "14"
[[redirects]]
  from = "seo/2021/03/15/how-to-extract-urls-from-sitemaps.html"
  to = "/how-to-extract-urls-from-sitemaps/"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
